# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4918abeeacd2f319629f1012eecafc4f56e256b76ef35a6b1d19393805c0250d5af88ecf076daf27d38c2e0b25a28bc3f8e377900155c4ee77ce3aaa1f0166b6

test:
  secret_key_base: b32f0968a83859842da5de08ba2f048f0b425bb70503040e19da8b7fc668874f70d4d7226acc3027d0752adfd5824204456705f826472af66d9933b1e13b82a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
